tdd_exercise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crossword_drill/', include('xword_data.urls')),
    path("", RedirectView.as_view(url='/crossword_drill/'))
]

xword_data/urls.py
from . import views
from .views import DrillView, AnswerView
from django.urls import path

app_name = 'xword_data'
urlpatterns = [
    path('', DrillView.as_view(), name="index"),
    path('clue_reveal/<int:entry_id>/<int:clue_id>/<int:puzzle_id>', DrillView.as_view(), name="reveal_answer"),
    path('correct_answer_reveal/<int:entry_id>/<int:clue_id>/<int:puzzle_id>', AnswerView.as_view(), name="answer_reveal"),
    path('escape-hatch/<int:entry_id>/<int:clue_id>/<int:puzzle_id>', views.escape_hatch, name="escape-hatch")
]

xword_data/models.py
from django.db import models


# Create your models here.
class Puzzle(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    date = models.DateField()
    byline = models.CharField(max_length=255)
    publisher = models.CharField(max_length=12)


class Entry(models.Model):
    entry_text = models.CharField(unique=True, max_length=50)


class Clue(models.Model):
    entry = models.IntegerField()
    puzzle = models.IntegerField()
    clue_text = models.TextField(max_length=512)
    theme = models.BooleanField(default=False)

xword_data/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.views import View
import random
from .models import Clue, Puzzle, Entry


# Create your views here.
class DrillView(View):
    def get(self, request):
        clues = Clue.objects.all()
        display_clue = random.choice(clues)
        print(display_clue.clue_text)
        entry = Entry.objects.get(id=display_clue.entry)
        puzzle = Puzzle.objects.get(id=display_clue.puzzle)
        print(entry.entry_text)
        print(puzzle.title)
        context = {
            'display_clue': display_clue,
            'entry': entry,
            'puzzle': puzzle,
            'reveal_click': False
        }
        return render(request, 'base.html', context)

    def post(self, request, entry_id, clue_id, puzzle_id):
        guess = request.POST['answer']
        entry = Entry.objects.get(id=entry_id)
        puzzle = Puzzle.objects.get(id=puzzle_id)
        clue = Clue.objects.get(id=clue_id)
        if guess == entry.entry_text:
            return redirect(f'/crossword_drill/correct_answer_reveal/{entry.id}/{clue.id}/{puzzle.id}')
        else:
            messages.error(request, 'Answer is incorrect. Give it another go!')
            context = {
                'display_clue': clue,
                'entry': entry,
                'puzzle': puzzle,
                'reveal_click': False
            }
            return render(request, 'base.html', context)


def escape_hatch(request, entry_id, clue_id, puzzle_id):
    entry = Entry.objects.get(id=entry_id)
    puzzle = Puzzle.objects.get(id=puzzle_id)
    clue = Clue.objects.get(id=clue_id)
    context = {
        'display_clue': clue,
        'entry': entry,
        'puzzle': puzzle,
        'reveal_click': True
    }
    return render(request, 'base.html', context)


class AnswerView(View):
    def get(self, request, entry_id, clue_id, puzzle_id):
        entry_ = Entry.objects.get(id=entry_id)
        puzzle = Puzzle.objects.get(id=puzzle_id)
        clue = Clue.objects.get(id=clue_id)
        clues = Clue.objects.filter(clue_text=clue.clue_text)
        entries = Entry.objects.all()
        hold_entry_dict = {}
        hold_entry_list = []
        count = 0
        for clue in clues:
            for entry_x in entries:
                if entry_x.id == clue.entry:
                    if len(hold_entry_list) == 0:
                        hold_entry_list.append(entry_x.entry_text)
                        count = count + 1
                        hold_entry_dict[entry_x.entry_text] = count
                    elif len(hold_entry_list) > 0:
                        if entry_x.entry_text in hold_entry_list:
                            hold_entry_list.append(entry_x.entry_text)
                            count = count + 1
                            hold_entry_dict[entry_x.entry_text] = count
                        elif entry_x.entry_text not in hold_entry_list:
                            hold_entry_list.append(entry_x.entry_text)
                            count = 1
                            hold_entry_dict[entry_x.entry_text] = count
        context = {
            'display_clue': clue,
            'puzzle': puzzle,
            'clues': clues,
            'entry_': entry_,
            'entries': hold_entry_dict,
        }
        print(context['entries'])
        print(hold_entry_list)
        return render(request, 'answer.html', context)

tdd_exercise/templates/answer.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/answer.css' %}">
{% endblock %}

{% block content %}
<div class="success-container">
    <div class="success-message">
        <h2><b id="congrats">Congrats!</b> You've guessed <i>{{entry_.entry_text}}</i> as the correct answer.</h2>
        <h3>Here's some additional information about the clue:</h3>
    </div>
        <br/>
    <div class="additional-info">
        <div class="drill-info">
            <ul>
                <li id="puzzle">Puzzle</li>
                <hr>
                <ul>
                    {% if title != None %}
                    <li><b>Title</b>: {{puzzle.title}}</li>
                    {% endif %}
                    <li><b>Byline</b>: {{puzzle.byline}}</li>
                    <li><b>Publisher</b>: {{puzzle.publisher}}</li>
                    <li><b>Date</b>: {{puzzle.date}}</li>
                </ul>
                <hr>
                <li id="clue">Clue</li>
                <hr>
                <ul>
                    <li><b>Clue Given</b>: {{display_clue.clue_text}}</li>
                </ul>
                <hr>
                <li id="entry">Entry</li>
                <hr>
                <ul>
                    <li><b>Answer</b>: {{entry_.entry_text}}</li>
                </ul>
            </ul>
        </div>
        {% if clues|length > 1 %}
        <div class="list-of-occurrences">
            <table class="table table-dark table-hover" id="entry-data-table">
                <thead>
                    <tr>
                        <th>Associated Entries</th>
                        <th>Occurrences</th>
                    </tr>
                </thead>
                <tbody>
                {% for entry, value in entries.items %}
                    <tr>
                        <td>{{entry}}</td>
                        <td>{{value}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <h4>This clue has only one occurrence</h4>
        {% endif %}
    </div>
    <div class="play-again">
        <button class="btn btn-primary"><a href="{% url 'xword_data:index' %}" id="play-again">Play Again?</a></button>
    </div>
</div>
{% endblock %}

tdd_exercise/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Crossword puzzle TDD exercise.">
    <title>{% block title %}Crossword Exercise{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    {% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/clue.css' %}"/>
    {% endblock %}
  </head>

  <body>
    <!-- Begin page content -->
    <main role="main" class="container">
      {% block content %}
      <div class="clue-container">
        <div class="clue-header">
          <h1>Random Clue</h1>
        </div>
        <div class="clue-form">
          <div class="clue">
            <h3>{{display_clue.clue_text}}</h3>
            <p>Word Length: {{entry.entry_text|length}}</p>
            <p>From Puzzle: {{puzzle.title}}</p>
          </div>
          <form method="post" action="{% url 'xword_data:reveal_answer' entry.id display_clue.id puzzle.id%}">
            {% csrf_token %}
            <div class="form-group">
              <input class="form-control" type="text" name="answer" id="_guess"/>
              <div class="clue-submit-button">
                <input class="btn btn-outline-warning" type="submit" id="submit-guess" value="Answer"/>
              </div>
              <br/>
              {% if reveal_click == False %}
              <div class="escape-hatch">
                <button class="btn btn-secondary" id="reveal-button"><a href="{% url 'xword_data:escape-hatch' entry.id display_clue.id puzzle.id %}" id="escape-hatch">Reveal Answer</a></button>
              </div>
              {% else %}
              <div class="escape-hatch">
                <h4>{{entry.entry_text}}</h4>
              </div>
              {% endif %}
            </div>
          </form>
        </div>
      </div>
      <div class="message-alert">
        {% if messages %}
          {% for message in messages %}
            <p>{{message}}</p>
          {% endfor %}
        {% endif %}
      </div>
      {% endblock %}
    </main>
  </body>
</html>